---
title: "Tucker_Prairie_Flora_Changes"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, eval=TRUE, echo=TRUE, warning=TRUE, message=FALSE}

## Clear environment 
rm(list=ls())

## Libraries
# Import excel files

library(readxl)

# Data cleaning and visualization
library(tidyverse)

# Community ecology functions (NMDS, diversity indices, etc.)
library(vegan)

# Package needed to do contrasts
library(emmeans)

# Dimensions check for NMDS stress
library(goeveg)

# Needed in order to install and load the pairwiseAdonis package
## install.packages("devtools")
## library(devtools)
## install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")

# Function for pairwise PERMANOVA tests
library(pairwiseAdonis)


# Makes grided figures
library(cowplot)

# Functions that let you plot ordiellipse in ggplot
library(tcltk)
library(BiodiversityR)


# Function that repels geom_text so that text labels don't overlap
library(ggrepel)

library(mosaic)

```

```{r, eval=TRUE, echo=FALSE, warning=TRUE, message=FALSE}

# Data sets


setwd("~/Desktop/Tucker_Prairie_Flora")


TP_2019 <- read_excel("Tucker_2019_fall_cover.xlsx")

## Remove Transect 7
TP_2019 <- TP_2019 %>% 
  filter(Transect != 7)

TP_1981 <- read_excel("Tucker_Flora_1981.xlsx")

TP_1978 <- read_excel("Rabinowitz_et_al_1981_Flowering.xlsx")
```



```{r}
### Lump so that the 2019 data is comparable to the 1981 data 

# Code to lump certain species together

cover_2019_to_merge_1981 <- TP_2019

for(i in 1:nrow(cover_2019_to_merge_1981)) {
  
  # Group all Juncus

  if(cover_2019_to_merge_1981[i,4] == "JUNBRA"){cover_2019_to_merge_1981[i,4] <- "JUNSPP"}

  
# Group all Muhlenbergia


   if(cover_2019_to_merge_1981[i,4] == "MUHGLA"){cover_2019_to_merge_1981[i,4] <- "MUHSPP"} 
  

}  


### Check that it changed the codes

sort(unique(cover_2019_to_merge_1981$SPP6))


### Sum everything by species by transect again 


cover_2019_to_merge_1981  <-cover_2019_to_merge_1981  %>%
              group_by(Transect, Plot, SPP6, Date) %>%
              summarize(Abundance = sum(Cover)) %>% 
              unite(Quadrat, c("Transect", "Plot"), sep = ".")



```


```{r}
### Lump so that the 1981 data is comparable to the 2019 data 

# Code to lump certain species together

cover_1981_to_merge_2019 <- TP_1981

for(i in 1:nrow(cover_1981_to_merge_2019)){
  
  # Group all Carex

  ## CARANN
  ## CARCOM
  ## CARCON
  ## CARFES
  ## CARSPP1
  ## CARSPP2
  ## CARSPP3
  ## CARSPP4
  ## CARSPP5
  ## CARSPP6
  
  if(cover_1981_to_merge_2019[i,1] == "CARANN"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP6"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARCOM"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARCON"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARFES"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP1"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP2"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP3"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP4"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}
  if(cover_1981_to_merge_2019[i,1] == "CARSPP5"){cover_1981_to_merge_2019[i,1] <- "CARSPP"}

  
# Group all Desmodium
  ## DESMIL

     if(cover_1981_to_merge_2019[i,1] == "DESMIL"){cover_1981_to_merge_2019[i,1] <- "DESSPP"} 
  
# Group all Juncus
  ## JUNMAR
  ## JUNSPP1
  ## JUNSPP2
  ## JUNTEN
  
  if(cover_1981_to_merge_2019[i,1] == "JUNMAR"){cover_1981_to_merge_2019[i,1] <- "JUNSPP"}
  if(cover_1981_to_merge_2019[i,1] == "JUNSPP1"){cover_1981_to_merge_2019[i,1] <- "JUNSPP"}
  if(cover_1981_to_merge_2019[i,1] == "JUNSPP2"){cover_1981_to_merge_2019[i,1] <- "JUNSPP"}
  if(cover_1981_to_merge_2019[i,1] == "JUNTEN"){cover_1981_to_merge_2019[i,1] <- "JUNSPP"}

# Group all Ulmus
  ## ULMAME

  if(cover_1981_to_merge_2019[i,1] == "ULMAME"){cover_1981_to_merge_2019[i,1] <- "ULMSPP"}
  
  # Group all Vernonia
  ## VERBAL
  
  if(cover_1981_to_merge_2019[i,1] == "VERBAL"){cover_1981_to_merge_2019[i,1] <- "VERSPP"}
  
}  

### Check that it changed the codes

sort(unique(cover_1981_to_merge_2019$SPP6))


### Sum everything by species by transect again 

cover_1981_to_merge_2019$Stems <- as.numeric(cover_1981_to_merge_2019$Stems)
cover_1981_to_merge_2019$Quadrat <- as.character(cover_1981_to_merge_2019$Quadrat)

cover_1981_to_merge_2019  <- cover_1981_to_merge_2019  %>%
              group_by(SPP6, Quadrat, Date) %>%
              summarize(Abundance = sum(Stems))

```

```{r}
All_Cover <- full_join(cover_1981_to_merge_2019 , cover_2019_to_merge_1981)

sort(unique(All_Cover $SPP6))


## no unknowns 

### There is no way of ever identifying their unknowns and their unknowns might be my knowns? Vice versa. So I removed them from the analysis

All_Cover_NU <- filter(All_Cover, !grepl('UNK', SPP6))


sort(unique(All_Cover_NU $SPP6))


```

```{r}
### Identified species richness per m^2

Species_Richness <- All_Cover_NU  %>% 
  group_by(Quadrat, Date) %>% 
  summarize(species_richness = n_distinct(SPP6))


#### Mean species richness between dates

Summary_stats_SR <- Species_Richness %>% 
  group_by(Date) %>% 
  summarize(mean_SR = mean(species_richness), SD_SR = sd(species_richness))


### There is little to no difference between years
Summary_stats_SR


#### No statistical difference in richness between 1981 and 2019 
species_richness.mod <- glm(species_richness ~ Date, family="poisson", data = Species_Richness)

library(car)
Anova(species_richness.mod, type = 3)

```
### Composition Analysis



```{r, results = 'hide',echo = FALSE, message = FALSE, warning = FALSE}

### Analysis 3: Data Wrangling
All_Cover_NU_Long <- All_Cover_NU  %>% 
  
# Make new column named "DateQuadrat" to make a unique ID for each transect at each site
## (e.g. 1981 Quadrat 2 = 1981_2)
  
  unite("DateQuadrat", Date:Quadrat, sep = "_", remove = FALSE)

  
All_Cover_NU_wide_full <- spread(All_Cover_NU_Long, SPP6, Abundance, fill = 0)


# ----------

# Remove all columns that isn't a species ID or Site

All_Cover_NU_wide <- All_Cover_NU_wide_full[, -c(2,3)]

# Make row labels DateQuadrat
All_Cover_NU_wide_labs   <- All_Cover_NU_wide[,-1]
row.names(All_Cover_NU_wide_labs) <-  All_Cover_NU_wide$DateQuadrat

# Convert into matrix
com_mat <- data.matrix(All_Cover_NU_wide_labs)


### Data frame to store non-species info

All_Cover_NU_wide_info <- All_Cover_NU_wide_full[, c(1,2,3)]
```

### Analysis: NMDS

Code below creates Figure 4.

```{r, results = 'hide', echo = FALSE, message = FALSE, warning = FALSE}

# Standardize the community matrix
## By presence/absence

com_mat_pa <- decostand(com_mat, "pa")
```

```{r, results = 'hide', echo = FALSE, message = FALSE, warning = FALSE, fig.show='hide'}

# Check the number of dimensions needed for the NMDS  (write the result of this test)

## Bray-Curtis dissimilarity
dimcheckMDS(com_mat_pa, distance = "jaccard", k=6, trymax= 50, autotransform = FALSE)

###
## *** Best solution with three dimensions
```

```{r, echo = FALSE, results = 'hide', echo = FALSE, message = FALSE, warning = FALSE}
set.seed(5)
Jac_NMDS <- metaMDS(com_mat_pa, distance = "jaccard", k=3, try=1000, trymax = 1000, autotransform =  FALSE)
```

```{r, results = 'hide', message = FALSE, echo = FALSE, warning = FALSE}
set.seed(5)
### Looks at which species were the most influential in driving the observed patterns

inner.spp.fit <- envfit(Jac_NMDS, com_mat_pa, permutations = 5000, k = 3)

#head(inner.spp.fit)
```

```{r, results = 'hide', message = FALSE, echo = FALSE, warning = FALSE, fig.show='hide'}

# Make a grouping variable so I can match site names to the NMDS output
site = c(rep("TP_1981", 23), rep("TP_2019", 45))

# Put the NMDS scores into it's own dataframe 
scrs <- as.data.frame(scores(Jac_NMDS, display = "sites"))

# Match the NMDS scores to the right site labels
scrs <- cbind(scrs, site)

# Extracts the required scaling factor for the vector arrows
arrow_factor <- ordiArrowMul(inner.spp.fit)

# Take the envfit model and convert into a a dataframe (scaled)
spp.scrs <- as.data.frame(scores(inner.spp.fit, display = "vectors"))*arrow_factor

# Add the p values, R squared values to the envit model species score dataframe
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs), Pvalues = inner.spp.fit$vectors$pvals, R_squared = inner.spp.fit$vectors$r)


# Subset out species that had a p value <= 0.001 (since I think env fit truncates to 0.001)
spp.scrs.01 <- subset(spp.scrs, Pvalues < 0.0002)

```

```{r, results = 'hide', message = FALSE, echo = FALSE, warning = FALSE, fig.show='hide'}

# Only including this plot because I need to call the plot in order to obtain the ordiellipse object

plot(Jac_NMDS$points, xlim = c(-2, 2), ylim = c(-2, 2), col = alpha(0.5), xlab = "NMDS1", ylab = "NMDS2", cex.lab = 1.25, cex.axis = 1.25, bty="n")


# Store the ordiellipse data into a list
site.ellipses <- ordiellipse(Jac_NMDS, groups = site, display = "sites", kind = "se", conf = 0.95)


# Convert the ordiellipse data into a dataframe that I can plot in ggplot
site.ellipses.long2 <- ordiellipse.long(site.ellipses, grouping.name="site")
```



```{r, results = 'hide', message = FALSE, echo = FALSE, warning = FALSE, fig.width = 8, fig.height = 8}

# Plot the species scores + the NMDS results

NMDS_plot <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, color = site, fill = site, shape = site), size=2.5, alpha = 0.8) + 
  scale_shape_manual(name = "", values=c(23,24,22,21),breaks=c("TP_1981", "TP_2019"), labels = c("Remnant 1981", "Remnant 2019")) +
  scale_color_manual(name = "", values=c("#1f78b4", "#7ab1cf"), breaks=c("TP_1981", "TP_2019"), labels = c("Remnant 1981", "Remnant 2019"))  +
  scale_fill_manual(name = "", values=c("#1f78b4", "#a6cee3"), breaks=c("TP_1981", "TP_2019"), labels = c("Remnant 1981", "Remnant 2019")) +
  geom_polygon(data = site.ellipses.long2, aes(x = axis1, y=axis2, colour = site, fill =   after_scale(alpha(colour, 0.2))), size = 0.2, show.legend = FALSE) +
  coord_fixed() +
  geom_segment(data = spp.scrs.01, 
             aes(x = 0, xend = NMDS1 * arrow_factor, y = 0, yend = NMDS2* arrow_factor),
             arrow = arrow(length = unit(0.2, "cm")), colour = "#888888", alpha = 0.7) +
  geom_text_repel(data = spp.scrs.01, aes(x = NMDS1 * arrow_factor, y = NMDS2 * arrow_factor, 
                                          label = Species), size = 3, max.overlaps = getOption("ggrepel.max.overlaps", default = 50) ) +
  annotate("text", x = -.7, y = 1.1, label = "bold(Stress) == 0.16",
  parse = TRUE)+
  annotate("text", x = -.80, y = 1, label = "bold(K) == 3",
  parse = TRUE) +
  theme_classic() +
  theme(text=element_text(size=18), legend.key.size=unit(0.5, "cm"))



NMDS_plot
```

### Analysis 3: PERMANOVA

```{r, message = FALSE, echo = FALSE, warning = FALSE}


# Standardize using site total and bray-curtis
data.dist.jac <- vegdist(com_mat_pa, method = "jaccard")
veg_com <- data.frame(site, com_mat)
```

```{r, message = FALSE, echo = FALSE, warning = FALSE}


# PERMANOVA looking at differences in species composition between sites
veg_perma_mod_jac <- adonis2(data.dist.jac~as.factor(site), data=veg_com, method = "jaccard")
veg_perma_mod_jac

```
